In [1]:
import numpy as np
import pandas as pd
import random as random
from matplotlib import pyplot as plt
%matplotlib inline

In [68]:
n=100 # number of users
m=10 # number of movies
list_of_users=list(range(0,n))
list_of_movies=list(range(0,m))
list_of_timestamps=list(range(0,n*m))
matrix_of_ratings=np.reshape(list(0 for i in range(0, n*m)),(m,n)) # matrix of ratings with all '0' entries
set_of_ratings=np.linspace(0.5,5,10)

In [3]:
set_of_ratings

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [4]:
s=np.random.normal(0,1,size=100) #create 100 random numbers from SND
ratings=pd.cut(s,10,labels=set_of_ratings) # bin into 10 bins and return labels 
ratings=pd.Series(ratings) # create pd.Series out of returned object

#one-liner:
#ratings=pd.Series(pd.cut(np.random.normal(0,1,size=100),10,labels=set_of_ratings))

In [5]:
# plt.hist(ratings,bins=10)
# plt.show()
# plt.close()
# plt.hist(s,bins=20)

In [6]:
type(np.array(pd.cut(np.random.uniform(0,1,size=n),10,labels=set_of_ratings)))

numpy.ndarray

In [7]:
ratings=np.array(pd.cut(np.random.uniform(0,1,size=n),10,labels=set_of_ratings))
a=random.choice(('NaN',ratings[0]))
ratings[0]=a
ratings

array([nan, 1. , 3. , 5. , 2. , 5. , 1. , 3.5, 2.5, 0.5, 0.5, 0.5, 2.5,
       4.5, 4. , 0.5, 1.5, 1. , 3.5, 3.5, 4.5, 1.5, 1.5, 1. , 3.5, 5. ,
       0.5, 1. , 2.5, 4.5, 4. , 1.5, 4.5, 5. , 3.5, 3. , 1.5, 3.5, 0.5,
       0.5, 0.5, 4.5, 4. , 4. , 4.5, 5. , 2.5, 4.5, 2. , 1.5, 3. , 2.5,
       4.5, 2.5, 2.5, 4.5, 1. , 1.5, 4.5, 1. , 2. , 4. , 5. , 3.5, 2. ,
       4. , 3. , 3.5, 2.5, 4. , 4. , 3. , 2. , 3. , 3. , 0.5, 4.5, 1.5,
       5. , 4. , 3.5, 2. , 0.5, 1. , 2.5, 0.5, 5. , 1. , 5. , 4. , 2. ,
       1.5, 4.5, 0.5, 4. , 1. , 1.5, 1. , 3. , 5. ])

In [8]:
a=np.random.choice((0,1))
a

0

In [9]:
def create_ratings(dist='normal',n=100):
    if dist=='uniform':
        ratings=np.array(pd.cut(np.random.uniform(0,1,size=n),10,labels=set_of_ratings))
    if dist=='normal':
        ratings=np.array(pd.cut(np.random.normal(0,1,size=n),10,labels=set_of_ratings))
    #set on av. 50% of ratings to 'NaN'
    for i in range(n):
        ratings[i]=random.choice(('NaN',ratings[i]))  
    return ratings

In [10]:
def create_ratings_matrix(dist='normal',m=10):
    ratings_matrix=[]
    for i in range(m):
        ratings_matrix.append(create_ratings(dist))
    return pd.DataFrame(ratings_matrix)

In [54]:
#Create ratings matrix
ratings_matrix=create_ratings_matrix('uniform')
#Unstack ratings matrix
ratings_matrix=pd.DataFrame(ratings_matrix.unstack())
#Create dataframe from list_of_timestamps
list_of_timestamps=pd.DataFrame(list_of_timestamps)
# Add timestamps(index) to unstacked ratings_maxtrix
ratings_matrix['index']=list_of_timestamps
#Rename colums and set index
ratings_matrix.columns=['UserId','movieId','rating','index']
ratings_matrix.set_index('index',inplace=True)

In [85]:
ratings_matrix

UserId  movieId  rating
index                         
0           0        0     NaN
1           0        1     NaN
2           0        2     NaN
3           0        3     NaN
4           0        4     NaN
...       ...      ...     ...
995        99        5     NaN
996        99        6     NaN
997        99        7     NaN
998        99        8     4.5
999        99        9     NaN

[1000 rows x 3 columns]

In [13]:
#plt.hist(create_ratings(),10)

In [14]:
#matrix_of_ratings

In [15]:
# create artifical ratings for each movie
# relevant paramters: mean, std, no of ratings

random_ratings=[]
def rate_movie(movie):
    for i in range(0,n):
        random_ratings.append(round(np.random.uniform(1,5)))
    matrix_of_ratings[movie]=random_ratings
    

In [16]:
rate_movie(0)

In [17]:
matrix_of_ratings[0]

array([2, 4, 3, 3, 1, 1, 2, 2, 2, 3, 4, 1, 3, 1, 3, 4, 2, 4, 5, 5, 4, 4,
       2, 2, 3, 4, 4, 2, 1, 4, 5, 5, 1, 4, 3, 3, 3, 2, 5, 3, 2, 4, 1, 2,
       2, 5, 5, 3, 3, 2, 3, 4, 4, 2, 2, 3, 3, 3, 3, 4, 3, 4, 2, 1, 5, 4,
       4, 1, 4, 1, 3, 4, 4, 2, 3, 1, 4, 3, 4, 1, 5, 2, 4, 4, 2, 5, 3, 5,
       4, 3, 2, 2, 2, 4, 4, 4, 2, 4, 3, 5])

In [18]:
def create_user():
    pass

In [19]:
def create_movies():
    pass